### ISSUE TITLE
Pasting images

### ISSUE THREAD

**Issue by Cupbox** [BlueGreenMagick/Edit-Field-During-Review-Cloze#3] opened 2020-01-10 10:11 UTC
Hello.
Currently pasting images pastes a resized version of the image as follows
`<!--StartFragment--><img src="image_url" alt="image_url" class="shrinkToFit transparent" width="x" height="y"><!--EndFragment-->`
Could this be changed to  
`<img src="image_url>"`?
Rationale: I use this addon to add image context quickly and then use the [Media Internalizer](https://ankiweb.net/shared/info/221033553) to localize them. However the resizing styling persists and I have to manually remove it.
Thanks.

**Comment by BlueGreenMagick** [comment] 2020-01-10 13:55
Hello, can I ask exactly how to reproduce this issue? I could not reproduce your issue from a random image. Info like where you copied from, os, Anki version.

And could you try and see if pasting through ctrl+shift+v shortcut work?

**Comment by Cupbox** [comment] 2020-01-10 17:17
Anki 2.1.16
Windows 10
For this [image](https://thumbs.dreamstime.com/z/lion-yawning-male-widely-showing-teeth-45995841.jpg), I get the following
![2020-01-10_22-01-12](https://user-images.githubusercontent.com/13769570/72171644-4eb3b800-33cb-11ea-88bf-99f42de5babf.gif)
ctrl+shift+v did not do anything with an image copied to the clipboard.
From a little testing, I think that when images are beyond window width (or specified, like 800px in my case), then the resizing is applied. A sufficiently large picture like [this](https://upload.wikimedia.org/wikipedia/commons/a/ae/Lion_Yawning.jpg) should do the same for you.

**Comment by BlueGreenMagick** [comment] 2020-01-24 08:05
Sorry for late response. I actually haven't managed to reproduce the issue with the above image, but I am positive that the latest update has fixed it. Could you try updating the addon and see if it works?

**Comment by Cupbox** [comment] 2020-01-24 14:13
Seem to have run into a bug. Images don't paste at all and while I can paste text, it throws the following error after I click outside the box
Debug info:
Anki 2.1.20 (d428b3b4) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 30, in cmd
  File "aqt\webview.py", line 96, in _onCmd
  File "aqt\webview.py", line 423, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-82>", line 2, in _linkHandler
  File "lib\site-packages\anki\hooks.py", line 506, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 503, in repl
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\385888438\__init__.py", line 232, in myLinkHandler
    reviewer.card._getQA(reload=True)
AttributeError: 'Card' object has no attribute '_getQA'

**Comment by BlueGreenMagick** [comment] 2020-01-26 12:28
Thanks for spotting and reporting both issues! First error was because of a change of code in Anki 2.1.20 which was addressed in the update and the second was an oversight of mine.

Both was fixed in the recent update and should hopefully work without an issue!

**Comment by Cupbox** [comment] 2020-01-26 12:54
Thank you! Working perfectly. 
Oddly enough, after successfully pasting an image it throws the following message.
![2020-01-26_17-41-01](https://user-images.githubusercontent.com/13769570/73135493-bfe5a300-403a-11ea-8837-8c36c6162b6c.png)
The edit(image) is in fact saved normally

**Comment by DoctorToBeIn23** [comment] 2020-01-27 01:01
I am on mac and cannot past any screen shots that I save to my clipboard...

**Comment by BlueGreenMagick** [comment] 2020-01-27 01:24
@DoctorToBeIn23 Can I ask if you are getting any error messages? Or if you are using other addons whether it works when you disable all addons except this one?

**Comment by DoctorToBeIn23** [comment] 2020-01-27 02:26
No error messages and I have tried with only this add on enabled and still same issue

**Comment by BlueGreenMagick** [comment] 2020-01-27 03:36
1. Do you have no problem pasting the same image when pasting in editor? 
2. Are there javascript functions/variables in your note type? Maybe some of it has the same name as those defined in this addon?

If not, I am really clueless to why it doesn't work. I somewhat copy pasted the code from Anki so it should have worked. I will probably have to modify the code so when encountering error, will paste without filtering html.

**Comment by DoctorToBeIn23** [comment] 2020-01-27 04:04
1. No sir
2. I have no idea what this means? Sorry I am no coder... I can easily go in though and command+C an image on google and paste it in. It is only the screen shots from Command+Shift+4 then holding control (to copy it to the clip board) and pasting.

**Comment by BlueGreenMagick** [comment] 2020-01-27 04:20
@DoctorToBeIn23 Could you try updating the addon and see if it works? I'm still not sure why the issue happens, so I had it skip processing paste when it encounters an error. It should hopefully work

**Comment by BlueGreenMagick** [comment] 2020-01-27 10:43
Both issues should have been fixed with the latest update. Please check it out and tell me if there's still issues

**Comment by AnKingMed** [comment] 2020-01-27 13:10
I just tried the new update and I'm having the same issue on Mac. I can paste from anything I've copied off google, but I can't paste off a screenshot to the clipboard

**Comment by DoctorToBeIn23** [comment] 2020-01-27 13:11
I updated, disabled all my add ons but this one, restarted, and still same issue

**Comment by BlueGreenMagick** [comment] 2020-01-28 11:58
I do not have a mac, so I am not sure what is happening under the hood. If you could try pasting a screenshot with the attached addon installed (and other edit field during review addons disabled), and tell me what message it spits out (one in a popup and another on Anki main window), I'd be very grateful and should help with this issue a lot.

[debug-paste.ankiaddon.zip](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/files/4122212/debug-paste.ankiaddon.zip)

**Comment by DoctorToBeIn23** [comment] 2020-01-28 16:10
![image](https://user-images.githubusercontent.com/60248099/73281939-f7289100-41ad-11ea-864e-93787b561f8e.png)

application/x-qt-image Files

**Comment by BlueGreenMagick** [comment] 2020-01-28 20:34
Thank you! The updated addon should fix the issue.

**Comment by AnKingMed** [comment] 2020-01-28 20:43
Works great now! Thanks for the quick fix!

**Comment by DoctorToBeIn23** [comment] 2020-01-28 21:19
Thank you veryyyyyy much!!! Do you know why when I take a screen shot of an image and paste it/edit it in it is larger than the original image?

**Comment by BlueGreenMagick** [comment] 2020-01-28 21:28
Good to know it works!

I would guess that your screenshot software is viewing the image to you zoomed out. According to this mac screenshot could have bigger dimension than original.

https://apple.stackexchange.com/questions/133249/screenshot-file-much-larger-dimensionally-than-original

**Closed by BlueGreenMagick** 2020-01-28 21:28 UTC
