### ISSUE TITLE
Resize not working on latest beta

### ISSUE THREAD

**Issue by AnKingMed** [BlueGreenMagick/Edit-Field-During-Review-Cloze#55] opened 2021-07-27 12:31 UTC
I tried with just this add-on installed on the latest beta (release candidate 2) and the resize function isn't working. I'm not sure how I actually got this error because it only occurred once, but it was when I tried to resize things

> Caught exception:
> Traceback (most recent call last):
>   File "aqt/webview.py", line 41, in cmd
>   File "aqt/webview.py", line 139, in _onCmd
>   File "aqt/webview.py", line 586, in _onBridgeCmd
>   File "aqt/hooks_gen.py", line 3927, in __call__
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 126, in handle_pycmd_message
>     reload_reviewer(reviewer)
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/385888438/reviewer.py", line 105, in reload_reviewer
>     reviewer._showAnswer()
>   File "decorator.py", line 232, in fun
>   File "anki/hooks.py", line 89, in decorator_wrapper
>   File "anki/hooks.py", line 86, in repl
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1409134430/__init__.py", line 36, in noEasy
>     if self.card.timeTaken() < getConfig("timeout") * 1000:
>   File "anki/cards.py", line 190, in time_taken
> TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

**Comment by BlueGreenMagick** [comment] 2021-07-28 07:09
This looks like a conflict with the [noeasy addon](https://ankiweb.net/shared/info/1409134430). I'm not sure how/why the conflict happens (maybe a race condition?), but closing the issue because that addon is a rather obscure one.

**Comment by AnKingMed** [comment] 2021-07-28 11:57
Weird... I believe the issue still remains though. The error code must have been from that add-on, but Edit Field During Review Cloze still isn't able to resize images from the editor like it used to be able

**Comment by BlueGreenMagick** [comment] 2021-07-28 13:14
I've confirmed that this issue ***does*** exist using the latest Anki master branch. Maybe related to this commit: https://github.com/ankitects/anki/commit/5cbb582d0b62259aceb25ddd62e133b6a4cf62c1

**Comment by BlueGreenMagick** [comment] 2021-07-30 09:16
Fixed with https://github.com/ankitects/anki/pull/1314

**Closed by BlueGreenMagick** 2021-07-30 09:16 UTC
